#Vincent Johnson, notes
lst1 = {
    "lst2": {
        "lst3": {
            "lst4": {
                "lst5": {
                    "lst6": {
                        "lst7": {
                            "lst8": {
                                "lst9": {
                                    "lst10": {
                                        "lst11": {
                                            "lst12": {
                                                "lst13": {
                                                    "lst14": {
                                                        "lst15": {
                                                            "lst 16": {
                                                                "lst17": {
                                                                    "lst18": {
                                                                        "lst19": {
                                                                            "lst20": {
                                                                                "lst21": {
                                                                                    "lst22": {
                                                                                        "lst23": {
                                                                                            "lst24": {
                                                                                                "lst25": {
                                                                                                    "lst26": {
                                                                                                        "lst27": {
                                                                                                            "lst28": {
                                                                                                                "lst29": {
                                                                                                                    "lst30": {
                                                                                                                        "lst31": {
                                                                                                                            "lst32": {
                                                                                                                                "lst33": {
                                                                                                                                    "lst34": {
                                                                                                                                        "lst35": {
                                                                                                                                            "lst36": {
                                                                                                                                                "lst37": {
                                                                                                                                                    "lst38": {
                                                                                                                                                        "lst39": {
                                                                                                                                                            "lst40": {
                                                                                                                                                                "lst41": {
                                                                                                                                                                    "lst42": {
                                                                                                                                                                        "lst43": {
                                                                                                                                                                            "lst44": {
                                                                                                                                                                                "lst45": {
                                                                                                                                                                                    "lst46": {
                                                                                                                                                                                        "lst47": {
                                                                                                                                                                                            "lst48": {
                                                                                                                                                                                                "lst49": {
                                                                                                                                                                                                    "lst50": {
                                                                                                                                                                                                        "lst51": {
                                                                                                                                                                                                            "lst52": {
                                                                                                                                                                                                                "lst53": {
                                                                                                                                                                                                                    "lst54": {
                                                                                                                                                                                                                        "lst55": {
                                                                                                                                                                                                                            "lst56": {
                                                                                                                                                                                                                                "lst57": {
                                                                                                                                                                                                                                    "lst58": {
                                                                                                                                                                                                                                        "lst59": {
                                                                                                                                                                                                                                            "lst60": {
                                                                                                                                                                                                                                                "lst61": {
                                                                                                                                                                                                                                                    "lst62": {
                                                                                                                                                                                                                                                        "lst63": {
                                                                                                                                                                                                                                                            "lst64": {
                                                                                                                                                                                                                                                                "lst65": {
                                                                                                                                                                                                                                                                    "lst66": {
                                                                                                                                                                                                                                                                        "lst67": {
                                                                                                                                                                                                                                                                            "lst68": {
                                                                                                                                                                                                                                                                                "lst69": {
                                                                                                                                                                                                                                                                                    "lst70": {
                                                                                                                                                                                                                                                                                        "lst71": {
                                                                                                                                                                                                                                                                                            "lst72": {
                                                                                                                                                                                                                                                                                                "lst73": {
                                                                                                                                                                                                                                                                                                    "lst74": {
                                                                                                                                                                                                                                                                                                        "lst75": {
                                                                                                                                                                                                                                                                                                            "lst76": {
                                                                                                                                                                                                                                                                                                                "lst77": {
                                                                                                                                                                                                                                                                                                                    "lst78": {
                                                                                                                                                                                                                                                                                                                        "lst79": {
                                                                                                                                                                                                                                                                                                                            "lst80": {
                                                                                                                                                                                                                                                                                                                                "lst81": {
                                                                                                                                                                                                                                                                                                                                    "lst82": {
                                                                                                                                                                                                                                                                                                                                        "lst83": {
                                                                                                                                                                                                                                                                                                                                            "lst84": {
                                                                                                                                                                                                                                                                                                                                                "lst85": {
                                                                                                                                                                                                                                                                                                                                                    "lst86": {
                                                                                                                                                                                                                                                                                                                                                        "lst87": {
                                                                                                                                                                                                                                                                                                                                                            "lst88": {
                                                                                                                                                                                                                                                                                                                                                                "lst89": {
                                                                                                                                                                                                                                                                                                                                                                    "lst90": {
                                                                                                                                                                                                                                                                                                                                                                        "lst91": {
                                                                                                                                                                                                                                                                                                                                                                            "lst92": {
                                                                                                                                                                                                                                                                                                                                                                                "lst93": {
                                                                                                                                                                                                                                                                                                                                                                                    "lst94": {
                                                                                                                                                                                                                                                                                                                                                                                        "lst95": {
                                                                                                                                                                                                                                                                                                                                                                                            "lst96": {
                                                                                                                                                                                                                                                                                                                                                                                                "lst97": {
                                                                                                                                                                                                                                                                                                                                                                                                    "lst98": {
                                                                                                                                                                                                                                                                                                                                                                                                        "lst99": {
                                                                                                                                                                                                                                                                                                                                                                                                            "lst100": {

                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                }
                                                                                                                                                                                                            }
                                                                                                                                                                                                        }
                                                                                                                                                                                                    }
                                                                                                                                                                                                }
                                                                                                                                                                                            }
                                                                                                                                                                                        }
                                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                }
                                                                                                                                                            }
                                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }